src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Email(message: 'Email format not valid')]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 25, nullable: true)]
    #[Assert\Length(min: 10, max: 10)]
    private ?string $birth_date = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $mobile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $social = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $street = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $county = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $zip_code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $annual_income = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'customers')]
    private ?UsState $birth_state = null;

    #[ORM\ManyToOne(inversedBy: 'state_customers')]
    private ?UsState $state = null;

    #[ORM\ManyToOne(inversedBy: 'customers')]
    private ?Agent $agent = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDisplayName() {
        return $this->first_name." ".$this->last_name;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBirthDate(): ?string
    {
        return $this->birth_date;
    }

    public function setBirthDate(?string $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->mobile;
    }

    public function setMobile(?string $mobile): self
    {
        $this->mobile = $mobile;

        return $this;
    }

    public function getSocial(): ?string
    {
        return $this->social;
    }

    public function setSocial(?string $social): self
    {
        $this->social = $social;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCounty(): ?string
    {
        return $this->county;
    }

    public function setCounty(?string $county): self
    {
        $this->county = $county;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(?string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }



    public function getAnnualIncome(): ?string
    {
        return $this->annual_income;
    }

    public function setAnnualIncome(?string $annual_income): self
    {
        $this->annual_income = $annual_income;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): self
    {
        $this->created_at = new \DateTime();

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getBirthState(): ?UsState
    {
        return $this->birth_state;
    }

    public function setBirthState(?UsState $birth_state): self
    {
        $this->birth_state = $birth_state;

        return $this;
    }

    public function getState(): ?UsState
    {
        return $this->state;
    }

    public function setState(?UsState $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getAgent(): ?Agent
    {
        return $this->agent;
    }

    public function setAgent(?Agent $agent): self
    {
        $this->agent = $agent;

        return $this;
    }
}

src/Form/CustomerType.php
<?php

namespace App\Form;

use App\Entity\Agency;
use App\Entity\Agent;
use App\Entity\Customer;
use App\Entity\Role;
use App\Entity\User;
use App\Entity\UsState;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CustomerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name',TextType::class, ['label'=>'First Name (*)','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2']],)
            ->add('last_name',TextType::class, ['label'=>'Last Name (*)','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('email', EmailType::class, ['label'=>'Email (*)','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('birth_date', TextType::class, ['label'=>'Birth Date',
                'attr' => ['placeholder' => 'dd/mm/yyyy','data-mask'=>'99/99/9999'],'label_attr'=>['class'=>'col-form-label']])
            ->add('phone',TextType::class, ['label'=>'Phone','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('mobile',TextType::class, ['label'=>'Mobil','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('social',TextType::class, ['label'=>'Social','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('street',TextType::class, ['label'=>'Street','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('city',TextType::class, ['label'=>'City','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('county',TextType::class, ['label'=>'County','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('zip_code',TextType::class, ['label'=>'Zip Code','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])
            ->add('annual_income',TextType::class, ['label'=>'Annual Income','label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']])

            ->add('agent', EntityType::class ,
                ['expanded'=>false,'multiple'=>false,'class' => Agent::class,'choice_label' => function($object){
                    return $object->getDisplayName();
                }, 'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.id', 'ASC');
                },
                    'attr'=>['class'=>'form-select', 'data-control'=>'select2'] ,'label'=>'Agent',
                    'label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']]
            )

            ->add('state', EntityType::class ,
                ['expanded'=>false,'multiple'=>false,'class' => UsState::class,'choice_label' => function($object){
                    return $object->getName();
                }, 'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.id', 'ASC');
                },
                    'attr'=>['class'=>'form-select', 'data-control'=>'select2'] ,'label'=>'State',
                    'label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']]
            )

            ->add('birth_state', EntityType::class ,
                ['expanded'=>false,'multiple'=>false,'class' => UsState::class,'choice_label' => function($object){
                    return $object->getName();
                }, 'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.id', 'ASC');
                },
                    'attr'=>['class'=>'form-select', 'data-control'=>'select2'] ,'label'=>'Birth State',
                    'label_attr'=>['class'=>'form-label fw-bolder text-dark fs-6 mb-2 mt-5']]
            )
            //TODO relation fields
        ;

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Customer::class,
        ]);
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\Agent;
use App\Entity\Customer;
use App\Entity\Role;
use App\Form\AgentType;
use App\Form\CustomerType;
use App\Form\RoleType;
use App\Repository\AgentRepository;
use App\Repository\CustomerRepository;
use App\Repository\RoleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/customers',)]
class CustomerController extends AbstractController
{

    private $em;

    /**
     * UserController constructor.
     * @param $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    #[Route('/list', name: 'list_customer', methods: ["GET","POST"])]
    public function customerList(PaginatorInterface $paginator, Request $request, CustomerRepository $repository): Response {

        $searh = "";
        $agents = $repository->getAll();
        if($request->isMethod('POST')){
            $searh=$request->get('search');
            if($searh!=""){
                $agents=$repository->findByExampleField($searh);
            }
        }

        $actions=[
            [
                "id"=>0,
                "name"=>"Delete",
            ]
        ];

        $pagination = $paginator->paginate(
            $agents,
            $request->query->getInt('page', 1),
            25
        );

        $delete_form_ajax = $this->createCustomForm('CUSTOMER_ID', 'DELETE', 'delete_customer');

        return $this->render('customer/index.html.twig', [
            'pagination' => $pagination, "actions"=>$actions, 'searh'=>$searh, 'delete_form_ajax' => $delete_form_ajax->createView()
        ]);
    }

    #[Route('/new', name: 'add_customer')]
    public function addCustomer(Request $request): Response{
        $customer = new Customer();
        $form=$this->createForm(CustomerType::class, $customer);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $this->em->persist($customer);
            $this->em->flush();

            $this->addFlash('success', 'Customer Created!');
            return $this->redirectToRoute('list_customer');
        }

        return $this->render('customer/add.html.twig', ['form'=>$form->createView(),'action'=>'New']);
    }

    #[Route('/edit/{id}', name: 'edit_customer', defaults:['id'=>null])]
    public function edit(Request $request, $id):Response {

        $customer = $this->em->getRepository('App\Entity\Customer')->find($id);
        $form=$this->createForm(CustomerType::class, $customer);

        if($customer==null){
            return $this->redirectToRoute('list_customer');
        }

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $this->em->persist($customer);
            $this->em->flush();

            $this->addFlash('success', 'Customer Updated!');
            return $this->redirectToRoute('list_customer');
        }

        return $this->render('customer/add.html.twig', ['form'=>$form->createView(),'action'=>'Edit']);
    }

    #[Route('/delete', name: 'delete_customer', methods: ["POST","DELETE"])]
    public function deleteAction(Request $request) {
        $id = $request->get('id');

        $user = $this->em->getRepository('App\Entity\Customer')->find($id);
        $removed = 0;
        $message = "";

        if ($user) {
            try {
                $this->em->remove($user);
                $this->em->flush();
                $removed = 1;
                $message = "The Customer has been Successfully removed";
            } catch (Exception $ex) {
                $removed = 0;
                $message = "The Customer can't be removed";
            }
        }

        return new Response(
            json_encode(array('removed' => $removed, 'message' => $message)), 200, array('Content-Type' => 'application/json')
        );
    }

    /**
     * @Route("/delete_multiple", name="delete_multiple_agent",methods={"POST","DELETE"})
     */
    public function deleteMultipleAction(Request $request) {

        $ids = $request->get('ids');
        $removed = 0;
        $message = "";

        foreach ($ids as $id) {
            $agent  = $this->em->getRepository('App\Entity\Customer')->find($id);

            if ($agent) {
                try {
                    $this->em->remove($agent);
                    $this->em->flush();
                    $removed = 1;
                    $message = "The Customers has been removed Successfully";
                } catch (Exception $ex) {
                    $removed = 0;
                    $message = "The Customers can't be removed";
                }
            }
        }

        return new Response(
            json_encode(array('removed' => $removed, 'message' => $message)), 200, array('Content-Type' => 'application/json')
        );
    }

    private function createCustomForm($id, $method, $route) {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl($route, array('id' => $id)))
            ->setMethod($method)
            ->getForm();
    }
}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Isureit - Customers{% endblock %}
{% block breadcrumb %}
    <div class="toolbar py-5" id="kt_toolbar">
        <div id="kt_toolbar_container" class="container-xxl d-flex flex-stack flex-wrap">
            <div class="page-title d-flex flex-column me-3">
                <h1 class="d-flex text-white fw-bolder my-1 fs-3"> {% trans %}customer.customers{% endtrans %}</h1>
                <ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 my-1">
                    <li class="breadcrumb-item text-white opacity-75">
                        <a href="#" class="text-white text-hover-primary">{% trans %}global.home{% endtrans %} </a>
                    </li>
                    <li class="breadcrumb-item">
                        <span class="bullet bg-white opacity-75 w-5px h-2px"></span>
                    </li>
                    <li class="breadcrumb-item text-white opacity-75"> {% trans %}customer.customer_list{% endtrans %}</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block body %}
    <div class="content-page">
        <div class="row">
            <div class="col-12">
                <!--begin::Card-->
                <div class="card">
                    <!--begin::Card header-->
                    <div class="card-body ">
                        {{ include('components/search_bar.html.twig',{ action_path: path('list_customer'),  link_path: path('add_customer'), add_btn_label: 'Add Customer' }) }}
                        {{ include('components/multiple_actions.html.twig',{ actions: actions }) }}
                        <div class="row mb-2">
                            <div class="col-12">
                                <div class="table-responsive" id="cont-table">
                                    <table id="table" class="table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4">
                                        <thead>
                                        <tr>
                                        <tr class="fw-bolder text-muted">
                                            <th class="w-10%">
                                                <input id="checkbox" class="form-check-input" type="checkbox" value="1" data-kt-check="true" data-kt-check-target=".widget-9-check" /> ID
                                            </th>
                                            <th {% if pagination.isSorted('u.first_name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Name', 'u.first_name') }}</th>
                                            <th {% if pagination.isSorted('u.email') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Email', 'u.email') }}</th>
                                            <th {% if pagination.isSorted('u.birth_date') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Birth Date', 'u.birth_date') }}</th>
                                            <th {% if pagination.isSorted('u.phone') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Phone', 'u.phone') }}</th>
                                            <th {% if pagination.isSorted('u.mobil') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Mobile', 'u.mobil') }}</th>
                                            <th {% if pagination.isSorted('u.social') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Social', 'u.social') }}</th>
                                            <th {% if pagination.isSorted('u.street') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Street', 'u.street') }}</th>
                                            <th {% if pagination.isSorted('u.city') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'City', 'u.city') }}</th>
                                            <th {% if pagination.isSorted('s.name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'State', 's.name') }}</th>
                                            <th {% if pagination.isSorted('bs.name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Birth State', 'bs.name') }}</th>
                                            <th {% if pagination.isSorted('u.zip_code') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Zip Code', 'u.zip_code') }}</th>
                                            <th {% if pagination.isSorted('a.name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Agent', 'a.name') }}</th>
                                            <th {% if pagination.isSorted('u.annual_income') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Anual Income', 'u.annual_income') }}</th>

                                            <th style="text-align: right;">Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for customer in pagination %}
                                            <tr id="row_{{ customer.id }}">
                                                <td>
                                                    <div class="form-check form-check-sm form-check-custom form-check-solid">
                                                        <input class="form-check-input widget-9-check" type="checkbox"
                                                               value="{{ customer.id }}"/> <span
                                                                style="margin-left: 6px;">{{ customer.id }}</span>
                                                    </div>
                                                </td>
                                                <td>{{ customer.getDisplayName }}</td>
                                                <td>{{ customer.email }}</td>
                                                <td>{{ customer.getBirthDate }}</td>
                                                <td>{{ customer.phone }}</td>
                                                <td>{{ customer.mobile }}</td>
                                                <td>{{ customer.social }}</td>
                                                <td>{{ customer.street }}</td>
                                                <td>{{ customer.city }}</td>
                                                <td>{{ customer.state.abbreviation }}</td>
                                                <td>{{ customer.birthstate.abbreviation }}</td>
                                                <td>{{ customer.getZipCode }}</td>
                                                <td>{{ customer.agent.getDisplayName }}</td>
                                                <td>{{ customer.annualIncome }}</td>
                                                <td style="text-align: right;">
                                                    {{ include('components/btn_edit.html.twig', { path: path('edit_customer',{'id':customer.id})  }) }}
                                                    {{ include('components/btn_delete.html.twig', { path: path('delete_customer',{id:customer.id}), id: customer.id}) }}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                    {# display navigation #}
                                    <div class="navigation">
                                        {{ knp_pagination_render(pagination) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <form action="{{ path('delete_customer') }}" method="post" id="delete_form">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
        <input type="hidden" id="customer" name="customer" value="customer">
    </form>
    {{ include('user/form.html.twig',{form:delete_form_ajax}) }}

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/role/delete.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function (e) {
            $('#roles_paginator').DataTable({
                "searching": false,
                "sort": false,
                "paging": false
            });

            $('#btn-search').click(function (e) {
                e.preventDefault()

                let searcrh_text = $('#filter-text-box').val()

                $('#form-search').submit()
            })

            $('.btn-delete').click(function (e) {
                e.preventDefault()

                var id = $(this).data('id')
                $('#customer').val(id)
            })

            $('#cont-table').on('click', '.btn-delete', function (e) {
                Swal.fire({
                    html: 'Do you want to delete this customer?',
                    icon: "warning",
                    buttonsStyling: false,
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: 'No, cancel',
                    customClass: {
                        confirmButton: "btn btn-success btn-confirm-delete",
                        cancelButton: 'btn btn-danger'
                    }
                }).then((result) => {
                    if (result.isConfirmed) {

                        var customer_id = $('#customer').val()
                        var tr = $('#row_' + customer_id);
                        var url = $('#delete_form').attr('action')

                        var data = {
                            id: customer_id
                        }

                        $.post(url, data, function (result) {

                            tr.fadeOut(500)

                            Swal.fire(
                                'Deleted!',
                                'The customer has been deleted.',
                                'success'
                            )
                        })
                    }
                })
            })


            $('.btn-execute').click(function (e) {
                e.preventDefault()

                let action = $('#multiple_actions').val();
                var selected = [];
                $('#table input[type="checkbox"]:checked').each(function() {
                    selected.push($(this).val());
                });

                if (action === '0'){
                    if (selected.length === 0) {
                        Swal.fire({
                            title: 'Delete seleted!',
                            html: 'Select at least one element please.',
                            icon: "warning",
                            confirmButtonText: "Ok",

                        })
                    }
                    var url = "/customers/delete_multiple";
                    var data = {
                        'ids': selected
                    }

                    console.log(url);

                    Swal.fire({
                        html: 'Do you want to delete this user?',
                        icon: "warning",
                        buttonsStyling: false,
                        showCancelButton: true,
                        confirmButtonText: "Yes, delete it!",
                        cancelButtonText: 'No, cancel',
                        customClass: {
                            confirmButton: "btn btn-success btn-confirm-delete",
                            cancelButton: 'btn btn-danger'
                        }
                    }).then((result) => {
                        if (result.isConfirmed) {

                            var role_id = $('#role').val()
                            var tr = $('#row_' + role_id);
                            var url = "/customers/delete_multiple";
                            var data = {
                                'ids': selected
                            }

                            $.post(url, data, function (result) {

                                selected.forEach(rol => {
                                    var tr = $('#row_' + rol);
                                    tr.fadeOut(500)
                                })

                                Swal.fire(
                                    'Deleted!',
                                    'The customers has been deleted.',
                                    'success'
                                )
                            })
                        }
                    })
                }

                console.log(action)
                console.log(selected)
            })
        });
    </script>
{% endblock %}