src/Entity/Agent.php
<?php

namespace App\Entity;

use App\Repository\AgentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AgentRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Agent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    private ?string $first_name = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    private ?string $last_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Email(message: 'Email format not valid')]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $birth_date = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $mobil = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $social = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $street = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $county = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $zip_code = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $license = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $npn = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $agency_str = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $phone_ext = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'agent')]
    private ?UsState $state = null;

    #[ORM\ManyToOne(inversedBy: 'agents')]
    private ?Agency $agency = null;

    #[ORM\ManyToOne(inversedBy: 'agents')]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Carrier::class, inversedBy: 'agents')]
    private Collection $agent_carriers;

    #[ORM\ManyToMany(targetEntity: Ancillary::class, inversedBy: 'agents')]
    private Collection $agent_ancilliaries;

    #[ORM\OneToMany(mappedBy: 'agent', targetEntity: Customer::class)]
    private Collection $customers;

    public function __construct()
    {
        $this->agent_carriers = new ArrayCollection();
        $this->agent_ancilliaries = new ArrayCollection();
        $this->customers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBirthDate(): ?string
    {
        return $this->birth_date;
    }

    public function setBirthDate(?string $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getMobil(): ?string
    {
        return $this->mobil;
    }

    public function setMobil(?string $mobil): self
    {
        $this->mobil = $mobil;

        return $this;
    }

    public function getSocial(): ?string
    {
        return $this->social;
    }

    public function setSocial(?string $social): self
    {
        $this->social = $social;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCounty(): ?string
    {
        return $this->county;
    }

    public function setCounty(?string $county): self
    {
        $this->county = $county;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(?string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getLicense(): ?string
    {
        return $this->license;
    }

    public function setLicense(?string $license): self
    {
        $this->license = $license;

        return $this;
    }

    public function getNpn(): ?string
    {
        return $this->npn;
    }

    public function setNpn(?string $npn): self
    {
        $this->npn = $npn;

        return $this;
    }

    public function getAgencyStr(): ?string
    {
        return $this->agency_str;
    }

    public function setAgencyStr(?string $agency_str): self
    {
        $this->agency_str = $agency_str;

        return $this;
    }

    public function getPhoneExt(): ?string
    {
        return $this->phone_ext;
    }

    public function setPhoneExt(?string $phone_ext): self
    {
        $this->phone_ext = $phone_ext;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): self
    {
        $this->created_at = new \DateTime();

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getState(): ?UsState
    {
        return $this->state;
    }

    public function setState(?UsState $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getAgency(): ?Agency
    {
        return $this->agency;
    }

    public function setAgency(?Agency $agency): self
    {
        $this->agency = $agency;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Carrier>
     */
    public function getAgentCarriers(): Collection
    {
        return $this->agent_carriers;
    }

    public function addAgentCarrier(Carrier $agentCarrier): self
    {
        if (!$this->agent_carriers->contains($agentCarrier)) {
            $this->agent_carriers->add($agentCarrier);
        }

        return $this;
    }

    public function removeAgentCarrier(Carrier $agentCarrier): self
    {
        $this->agent_carriers->removeElement($agentCarrier);

        return $this;
    }

    /**
     * @return Collection<int, Ancillary>
     */
    public function getAgentAncilliaries(): Collection
    {
        return $this->agent_ancilliaries;
    }

    public function addAgentAncilliary(Ancillary $agentAncilliary): self
    {
        if (!$this->agent_ancilliaries->contains($agentAncilliary)) {
            $this->agent_ancilliaries->add($agentAncilliary);
        }

        return $this;
    }

    public function removeAgentAncilliary(Ancillary $agentAncilliary): self
    {
        $this->agent_ancilliaries->removeElement($agentAncilliary);

        return $this;
    }

    public function __toString() {
        return $this->first_name." ".$this->last_name;
    }

    public function getDisplayName() {
        return $this->first_name." ".$this->last_name;
    }

    /**
     * @return Collection<int, Customer>
     */
    public function getCustomers(): Collection
    {
        return $this->customers;
    }

    public function addCustomer(Customer $customer): self
    {
        if (!$this->customers->contains($customer)) {
            $this->customers->add($customer);
            $customer->setAgent($this);
        }

        return $this;
    }

    public function removeCustomer(Customer $customer): self
    {
        if ($this->customers->removeElement($customer)) {
            // set the owning side to null (unless already changed)
            if ($customer->getAgent() === $this) {
                $customer->setAgent(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping\OneToMany;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email(message: 'Email format not valid')]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank]
    #[Assert\Length(min: 6, max: 255)]
    private ?string $password = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column]
    private ?bool $enabled = null;

    #[ORM\ManyToMany(targetEntity: Role::class, inversedBy: 'users')]
    #[Assert\NotBlank]
    #[Assert\Count(min: 1,minMessage: 'You have to select at least one Role')]
    private Collection $user_roles;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Agent::class)]
    private Collection $agents;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Log::class)]
    private Collection $logs;

    /**
     * User constructor.
     * @param int|null $id
     * @param string|null $email
     * @param array $roles
     * @param string|null $password
     */
    public function __construct(?string $first_name=null, ?string $last_name=null, ?int $id=null, ?string $email=null,  ?string $password=null)
    {
        $this->first_name=$first_name;
        $this->last_name=$last_name;
        $this->id = $id;
        $this->email = $email;
        $this->password = $password;
        $this->user_roles = new ArrayCollection();
        $this->agents = new ArrayCollection();
        $this->logs = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $rolesList=$this->getUserRoles();
        $roles=array();

        if($rolesList!==null or $rolesList!==""){
            foreach ($rolesList as $rol){
                $roles[]=$rol->getName();
            }
        }

        return array_unique($roles);
    }

    /**
     * @see UserInterface
     */
    public function hasRole(String $role): bool
    {
        $rolesList=$this->getUserRoles();

        if($rolesList!==null or $rolesList!==""){
            foreach ($rolesList as $rol){
                if($rol->getName() == $role){
                    return true;
                }
            }
        }

        return false;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullName(){
        return $this->first_name.' '.$this->last_name;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): self
    {
        $this->created_at = new \DateTime();

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @return Collection<int, Role>
     */
    public function getUserRoles(): Collection
    {
        return $this->user_roles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->user_roles->contains($userRole)) {
            $this->user_roles[] = $userRole;
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        $this->user_roles->removeElement($userRole);

        return $this;
    }

    public function __toString() {
        return $this->first_name.' '.$this->last_name;
    }

    public function getDisplayName() {
        return $this->first_name.' '.$this->last_name;
    }

    /**
     * @return Collection<int, Agent>
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents->add($agent);
            $agent->setUser($this);
        }

        return $this;
    }

    public function removeAgent(Agent $agent): self
    {
        if ($this->agents->removeElement($agent)) {
            // set the owning side to null (unless already changed)
            if ($agent->getUser() === $this) {
                $agent->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Log>
     */
    public function getLogs(): Collection
    {
        return $this->logs;
    }

    public function addLog(Log $log): self
    {
        if (!$this->logs->contains($log)) {
            $this->logs->add($log);
            $log->setUser($this);
        }

        return $this;
    }

    public function removeLog(Log $log): self
    {
        if ($this->logs->removeElement($log)) {
            // set the owning side to null (unless already changed)
            if ($log->getUser() === $this) {
                $log->setUser(null);
            }
        }

        return $this;
    }

}

templates/client/add.html.twig
{% extends 'base.html.twig' %}
{% block title %}Isureit - {{ action }} Agency{% endblock %}
{% block breadcrumb %}
    <div class="toolbar py-5" id="kt_toolbar">
        <div id="kt_toolbar_container" class="container-xxl d-flex flex-stack flex-wrap">
            <div class="page-title d-flex flex-column me-3">
                <h1 class="d-flex text-white fw-bolder my-1 fs-3">{{ action }} Agency</h1>
                <ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 my-1">
                    <li class="breadcrumb-item text-white opacity-75">
                        <a href="{{ path('dashboard') }}" class="text-white text-hover-primary">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <span class="bullet bg-white opacity-75 w-5px h-2px"></span>
                    </li>
                    <li class="breadcrumb-item text-white opacity-75">
                        <a href="{{ path('list_agency') }}" class="text-white text-hover-primary">Agencies</a>
                    </li>
                    <li class="breadcrumb-item">
                        <span class="bullet bg-white opacity-75 w-5px h-2px"></span>
                    </li>
                    <li class="breadcrumb-item text-white opacity-75">{{ action }} agency</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block body %}
    <div class="content-page">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-9">
                                {{ form_start(form, {'attr': {'id':'form'}}) }}

                                {{ form_widget(form) }}

                                <div class="form-group row pt-10">
                                    <div class="col-12">
                                        <p class="text-danger font-weight-bold">(*) Fields required</p>
                                        <a href="#" class="btn btn-primary bnt-send"><i class="fas fa-save"></i>
                                            Save</a>
                                        <a href="{{ path('list_agency') }}" class="btn btn-danger"><i
                                                    class="fas fa-ban"></i> Cancel</a>
                                    </div>
                                </div>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
 {% block javascripts %}
     {{ parent() }}
     <script src="{{ asset('assets/js/scripts.bundle.js') }}"></script>

     <script type="text/javascript">
         $(document).ready(function (e) {

             $('.bnt-send').click(function (e) {

                 e.preventDefault();
                 $('#form').submit();
             })
         })
     </script>
 {% endblock %}

templates/client/form.html.twig
{{ form_start(form,{'attr':{'class':'form-delete','id':id|default('form')}})}}
{{ form_widget(form) }}
{{ form_end(form) }}

templates/client/view.html.twig
{% extends 'base.html.twig' %}
{% block title %} Isureit - Users!{% endblock %}
{% block breadcrumb %}
    {{ include('components/breadcrumb.html.twig',
        {
            item_level:2,
            main_section_title: "Client",
            parent_page_title: "Clients" ,
            link_path: 'client_list',
            page_title: "Client",
            action: action
        })
    }}
{% endblock %}
{% block body %}
    <div class="content-page">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col-12">
                                <div class="post d-flex flex-column-fluid" id="kt_post">
                                    <div id="kt_content_container" class="container-xxl">
                                        <div class="card mb-5 mb-xl-10" id="kt_profile_details_view">
                                            <div class="card-header cursor-pointer">
                                                <div class="card-title m-0">
                                                    <h3 class="fw-bolder m-0">Client Details
                                                        {% if client.customerSignature!=null  %}
                                                            <span class="text-success"> - In Progress</span>
                                                        {% else %}
                                                            <span class="text-danger"> - Not Yet Started</span>
                                                        {% endif %}
                                                    </h3>
                                                </div>
                                            </div>
                                            <div class="card-body p-9">

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Status</label>
                                                    <div class="col-lg-8">
                                                        <span class="fw-bolder fs-6 text-gray-800">{{ client.status.name }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Full Name</label>
                                                    <div class="col-lg-8">
                                                        <span class="fw-bolder fs-6 text-gray-800">{{ client.firstName }} {{ client.lastName }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">DOB</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.dateOfBirth }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Age</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.age }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Address</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.address }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Suite</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.suite }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">City</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.city }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">US State</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.state.name }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Zip Code</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.zipCode }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Family Size</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.familySize }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Marketplace (Y/N)</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        {% if client.isMarketPlace == true %}
                                                            <span class="fw-bolder fs-6 text-gray-800 me-2">Y</span>
                                                        {% else %}
                                                            <span class="fw-bolder fs-6 text-gray-800 me-2">N</span>
                                                        {% endif %}

                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Current Household Income on file</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.currentHouseHold }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Email</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.email }}</span>
                                                    </div>
                                                </div>

                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Phone Number</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ client.phone }}</span>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="assets/plugins/custom/datatables/datatables.bundle.js"></script>
    <script type="text/javascript">
        $(document).ready(function (e) {



        })
    </script>
{% endblock %}