src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping\OneToMany;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email(message: 'Email format not valid')]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank]
    #[Assert\Length(min: 6, max: 255)]
    private ?string $password = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column]
    private ?bool $enabled = null;

    #[ORM\ManyToMany(targetEntity: Role::class, inversedBy: 'users')]
    #[Assert\NotBlank]
    #[Assert\Count(min: 1,minMessage: 'You have to select at least one Role')]
    private Collection $user_roles;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Agent::class)]
    private Collection $agents;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Log::class)]
    private Collection $logs;

    /**
     * User constructor.
     * @param int|null $id
     * @param string|null $email
     * @param array $roles
     * @param string|null $password
     */
    public function __construct(?string $first_name=null, ?string $last_name=null, ?int $id=null, ?string $email=null,  ?string $password=null)
    {
        $this->first_name=$first_name;
        $this->last_name=$last_name;
        $this->id = $id;
        $this->email = $email;
        $this->password = $password;
        $this->user_roles = new ArrayCollection();
        $this->agents = new ArrayCollection();
        $this->logs = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $rolesList=$this->getUserRoles();
        $roles=array();

        if($rolesList!==null or $rolesList!==""){
            foreach ($rolesList as $rol){
                $roles[]=$rol->getName();
            }
        }

        return array_unique($roles);
    }

    /**
     * @see UserInterface
     */
    public function hasRole(String $role): bool
    {
        $rolesList=$this->getUserRoles();

        if($rolesList!==null or $rolesList!==""){
            foreach ($rolesList as $rol){
                if($rol->getName() == $role){
                    return true;
                }
            }
        }

        return false;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullName(){
        return $this->first_name.' '.$this->last_name;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): self
    {
        $this->created_at = new \DateTime();

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @return Collection<int, Role>
     */
    public function getUserRoles(): Collection
    {
        return $this->user_roles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->user_roles->contains($userRole)) {
            $this->user_roles[] = $userRole;
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        $this->user_roles->removeElement($userRole);

        return $this;
    }

    public function __toString() {
        return $this->first_name.' '.$this->last_name;
    }

    public function getDisplayName() {
        return $this->first_name.' '.$this->last_name;
    }

    /**
     * @return Collection<int, Agent>
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents->add($agent);
            $agent->setUser($this);
        }

        return $this;
    }

    public function removeAgent(Agent $agent): self
    {
        if ($this->agents->removeElement($agent)) {
            // set the owning side to null (unless already changed)
            if ($agent->getUser() === $this) {
                $agent->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Log>
     */
    public function getLogs(): Collection
    {
        return $this->logs;
    }

    public function addLog(Log $log): self
    {
        if (!$this->logs->contains($log)) {
            $this->logs->add($log);
            $log->setUser($this);
        }

        return $this;
    }

    public function removeLog(Log $log): self
    {
        if ($this->logs->removeElement($log)) {
            // set the owning side to null (unless already changed)
            if ($log->getUser() === $this) {
                $log->setUser(null);
            }
        }

        return $this;
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserEditType;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Service\LogService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/users')]
class UserController extends AbstractController
{
    private $em;
    private $log_service;

    public function __construct(EntityManagerInterface $em, LogService $log_service)
    {
        $this->em = $em;
        $this->log_service = $log_service;
    }

    #[Route('/list', name: 'list_user', methods: ["GET","POST"])]
    public function index(UserRepository $repository, TranslatorInterface $translator, PaginatorInterface $paginator, Request $request): Response
    {
        $searh="";
        $users=$repository->getAll();
        if($request->isMethod('POST')){
            $searh=$request->get('search');
            if($searh!=""){
                $users=$repository->findByExampleField($searh);
            }
        }

        $pagination = $paginator->paginate(
            $users,
            $request->query->getInt('page', 1),
            10
        );

        $delete_form_ajax = $this->createCustomForm('USER_ID', 'DELETE', 'delete_role');

        $actions=[
            [
                "id"=>0,
                "name"=>"delete"
            ]
        ];

        $this->log_service->add('List',null, 'User');

        return $this->render('user/index.html.twig', [
            'pagination' => $pagination,'delete_form_ajax' => $delete_form_ajax->createView(), "actions"=>$actions, 'searh'=>$searh
        ]);
    }

    #[Route('/new', name: 'add_user')]
    public function add(Request $request, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user=new User();

        $form=$this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $user->setRoles(['ROLE_USER']);
            $password=$form->get('password')->getData();

            $hashedPassword = $passwordHasher->hashPassword(
                $user,
                $password
            );

            $user->setPassword($hashedPassword);
            $this->em->persist($user);
            $this->em->flush();

            $this->log_service->add('Add',$user->getId(), 'User');

            return $this->redirectToRoute('list_user');
        }

        return $this->render('user/add.html.twig', [
            'form'=>$form->createView(), 'action'=>'New'
        ]);
    }

    #[Route('/edit/{id}', name: 'edit_user', defaults: ["id"=>null],  methods: ["GET", "POST"])]
    public function edit(Request $request, UserPasswordHasherInterface $passwordHasher, $id):Response {

        $user=$this->em->getRepository(User::class)->find($id);

        $form=$this->createForm(UserEditType::class,$user);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $this->em->persist($user);
            $this->em->flush();

            $this->log_service->add('Edit',$user->getId(), 'User');
            $this->addFlash('success', 'User Updated!');
            return $this->redirectToRoute('user');
        }

        return $this->render('user/add.html.twig',['action'=>'Edit','form'=>$form->createView()]);
    }

    #[Route('/view/{id}', name: 'view_user', defaults: ["id"=>null],  methods: ["GET"])]
    public function view($id):Response {

        $user=$this->em->getRepository(User::class)->find($id);

        $role=null;
        if($user->hasRole('ROLE_AGENT')){
            $role='Agent';
        }

        return $this->render('user/view.html.twig',['user'=>$user,'action'=>'View' ,'role'=>$role]);
    }

    #[Route('/delete', name: 'delete_user', methods: ["POST","DELETE"])]
    public function deleteAction(Request $request) {
        $id = $request->get('id');

        $user = $this->em->getRepository('App\Entity\User')->find($id);
        $removed = 0;
        $message = "";

        if ($user) {
            try {
                $this->em->remove($user);
                $this->em->flush();
                $removed = 1;

                $this->log_service->add('Delete',$user->getId(), 'User');

                $message = "The User has been Successfully removed";
            } catch (Exception $ex) {
                $removed = 0;
                $message = "The User can't be removed";
            }
        }

        return new Response(
            json_encode(array('removed' => $removed, 'message' => $message)), 200, array('Content-Type' => 'application/json')
        );
    }

    /**
     * @Route("/delete_multiple", name="delete_multiple_user",methods={"POST","DELETE"})
     */
    public function deleteMultipleAction(Request $request) {

        $ids = $request->get('ids');
        $removed = 0;
        $message = "";

        foreach ($ids as $id) {
            $user  = $this->em->getRepository('App\Entity\User')->find($id);

            if ($user) {
                try {
                    $this->em->remove($user);
                    $this->em->flush();
                    $removed = 1;

                    $this->log_service->add('Delete',$user->getId(), 'User');

                    $message = "The Users has been removed Successfully";
                } catch (Exception $ex) {
                    $removed = 0;
                    $message = "The Users can't be removed";
                }
            }
        }

        return new Response(
            json_encode(array('removed' => $removed, 'message' => $message)), 200, array('Content-Type' => 'application/json')
        );
    }


    private function createCustomForm($id, $method, $route) {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl($route, array('id' => $id)))
            ->setMethod($method)
            ->getForm();
    }

    public function userMenu(Request $request) {

        $user=$this->getUser();
        $full_name='';
        $email='';

        if($user!=null){
            $full_name=$user->getFullName();
            $email=$user->getEmail();
        }


        $locale = $request->getLocale();

        $current_language="English";
        if($locale=='es'){
            $current_language="Español";
        }

        return $this->render('user-menu.html.twig',['full_name'=>$full_name,'email'=>$email,'current_language'=>$current_language]);
    }
}

templates/user/add.html.twig
{% extends 'base.html.twig' %}
{% block title %}Isureit - {{ action}} User!{% endblock %}
{% block breadcrumb %}
    {{ include('components/breadcrumb.html.twig',
        {
            item_level:2,
            main_section_title: "User",
            parent_page_title: "Users" ,
            link_path: 'list_user',
            page_title: "User",
            action: action
        })
    }}
{% endblock %}
{% block body %}
    <div class="content-page">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-9">
                                {{ form_start(form, {'attr': {'id':'form'}}) }}
                                {{ form_widget(form) }}
                                {{ include('components/form-buttons.html.twig',
                                    {
                                        cancel_path: path('list_user'),
                                    })
                                }}
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
 {% block javascripts %}
     {{ parent()}}
     <script type="text/javascript">
         $(document).ready(function(e){
             $('.bnt-send').click(function(e){

                 e.preventDefault();
                 $('#form').submit();
             })
         })
     </script>
 {% endblock %}

templates/user/form.html.twig
{{ form_start(form,{'attr':{'class':'form-delete','id':id|default('form')}})}}
{{ form_widget(form) }}
{{ form_end(form) }}

templates/user/registration_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
   {{ form(registration_form) }}
{% endblock %}

templates/user/view.html.twig
{% extends 'base.html.twig' %}
{% block title %} Isureit - {{ action}} User!{% endblock %}
{% block breadcrumb %}
    {{ include('components/breadcrumb.html.twig',
        {
            item_level:2,
            main_section_title: "User",
            parent_page_title: "Users" ,
            link_path: path('list_user'),
            page_title: "User",
            action: action
        })
    }}
{% endblock %}
{% block body %}
    <div class="content-page">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col-12">
                                <!--begin::Post-->
                                <div class="post d-flex flex-column-fluid" id="kt_post">
                                    <!--begin::Container-->
                                    <div id="kt_content_container" class="container-xxl">
                                        <!--begin::Navbar-->
                                        <div class="card mb-5 mb-xl-10">
                                            <div class="card-body pt-9 pb-0">
                                                <!--begin::Details-->
                                                <div class="d-flex flex-wrap flex-sm-nowrap mb-3">
                                                    <!--begin::Info-->
                                                    <div class="flex-grow-1">
                                                        <!--begin::Title-->
                                                        <div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
                                                            <!--begin::User-->
                                                            <div class="d-flex flex-column">
                                                                <!--begin::Name-->
                                                                <div class="d-flex align-items-center mb-2">
                                                                    <a href="#" class="text-gray-900 text-hover-primary fs-2 fw-bolder me-1">{{ user.getFullName() }}</a>
                                                                    <a href="#">
                                                                        <!--begin::Svg Icon | path: icons/duotune/general/gen026.svg-->
                                                                        <span class="svg-icon svg-icon-1 svg-icon-primary">
																	        <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24">
																		        <path d="M10.0813 3.7242C10.8849 2.16438 13.1151 2.16438 13.9187 3.7242V3.7242C14.4016 4.66147 15.4909 5.1127 16.4951 4.79139V4.79139C18.1663 4.25668 19.7433 5.83365 19.2086 7.50485V7.50485C18.8873 8.50905 19.3385 9.59842 20.2758 10.0813V10.0813C21.8356 10.8849 21.8356 13.1151 20.2758 13.9187V13.9187C19.3385 14.4016 18.8873 15.491 19.2086 16.4951V16.4951C19.7433 18.1663 18.1663 19.7433 16.4951 19.2086V19.2086C15.491 18.8873 14.4016 19.3385 13.9187 20.2758V20.2758C13.1151 21.8356 10.8849 21.8356 10.0813 20.2758V20.2758C9.59842 19.3385 8.50905 18.8873 7.50485 19.2086V19.2086C5.83365 19.7433 4.25668 18.1663 4.79139 16.4951V16.4951C5.1127 15.491 4.66147 14.4016 3.7242 13.9187V13.9187C2.16438 13.1151 2.16438 10.8849 3.7242 10.0813V10.0813C4.66147 9.59842 5.1127 8.50905 4.79139 7.50485V7.50485C4.25668 5.83365 5.83365 4.25668 7.50485 4.79139V4.79139C8.50905 5.1127 9.59842 4.66147 10.0813 3.7242V3.7242Z" fill="#00A3FF" />
																		        <path class="permanent" d="M14.8563 9.1903C15.0606 8.94984 15.3771 8.9385 15.6175 9.14289C15.858 9.34728 15.8229 9.66433 15.6185 9.9048L11.863 14.6558C11.6554 14.9001 11.2876 14.9258 11.048 14.7128L8.47656 12.4271C8.24068 12.2174 8.21944 11.8563 8.42911 11.6204C8.63877 11.3845 8.99996 11.3633 9.23583 11.5729L11.3706 13.4705L14.8563 9.1903Z" fill="white" />
																	        </svg>
																        </span>
                                                                        <!--end::Svg Icon-->
                                                                    </a>
                                                                </div>
                                                                <!--end::Name-->
                                                                <!--begin::Info-->
                                                                <div class="d-flex flex-wrap fw-bold fs-6 mb-4 pe-2">
                                                                    {% if role %}
                                                                    <a href="#" class="d-flex align-items-center text-gray-400 text-hover-primary me-5 mb-2">
                                                                        <!--begin::Svg Icon | path: icons/duotune/communication/com006.svg-->
                                                                        <span class="svg-icon svg-icon-4 me-1">
																        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
																	        <path opacity="0.3" d="M22 12C22 17.5 17.5 22 12 22C6.5 22 2 17.5 2 12C2 6.5 6.5 2 12 2C17.5 2 22 6.5 22 12ZM12 7C10.3 7 9 8.3 9 10C9 11.7 10.3 13 12 13C13.7 13 15 11.7 15 10C15 8.3 13.7 7 12 7Z" fill="currentColor" />
																	        <path d="M12 22C14.6 22 17 21 18.7 19.4C17.9 16.9 15.2 15 12 15C8.8 15 6.09999 16.9 5.29999 19.4C6.99999 21 9.4 22 12 22Z" fill="currentColor" />
																        </svg>
															            </span>
                                                                        <!--end::Svg Icon-->{{ role }}</a>
                                                                    {% endif %}
                                                                    <a href="#" class="d-flex align-items-center text-gray-400 text-hover-primary me-5 mb-2">
                                                                        <!--begin::Svg Icon | path: icons/duotune/general/gen018.svg-->
                                                                        <span class="svg-icon svg-icon-4 me-1">
																        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
																	        <path opacity="0.3" d="M18.0624 15.3453L13.1624 20.7453C12.5624 21.4453 11.5624 21.4453 10.9624 20.7453L6.06242 15.3453C4.56242 13.6453 3.76242 11.4453 4.06242 8.94534C4.56242 5.34534 7.46242 2.44534 11.0624 2.04534C15.8624 1.54534 19.9624 5.24534 19.9624 9.94534C20.0624 12.0453 19.2624 13.9453 18.0624 15.3453Z" fill="currentColor" />
																	        <path d="M12.0624 13.0453C13.7193 13.0453 15.0624 11.7022 15.0624 10.0453C15.0624 8.38849 13.7193 7.04535 12.0624 7.04535C10.4056 7.04535 9.06241 8.38849 9.06241 10.0453C9.06241 11.7022 10.4056 13.0453 12.0624 13.0453Z" fill="currentColor" />
																        </svg>
															            </span>
                                                                        {#{% if agent %}
                                                                            {{ agent.getAddress }}
                                                                        {% endif %}#}
                                                                    </a>
                                                                    <a href="#" class="d-flex align-items-center text-gray-400 text-hover-primary mb-2">
                                                                        <!--begin::Svg Icon | path: icons/duotune/communication/com011.svg-->
                                                                        <span class="svg-icon svg-icon-4 me-1">
																<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
																	<path opacity="0.3" d="M21 19H3C2.4 19 2 18.6 2 18V6C2 5.4 2.4 5 3 5H21C21.6 5 22 5.4 22 6V18C22 18.6 21.6 19 21 19Z" fill="currentColor" />
																	<path d="M21 5H2.99999C2.69999 5 2.49999 5.10005 2.29999 5.30005L11.2 13.3C11.7 13.7 12.4 13.7 12.8 13.3L21.7 5.30005C21.5 5.10005 21.3 5 21 5Z" fill="currentColor" />
																</svg>
															</span>
                                                                        <!--end::Svg Icon-->{{ user.email }}</a>
                                                                </div>
                                                                <!--end::Info-->
                                                            </div>
                                                            <!--end::User-->
                                                        </div>
                                                        <!--end::Title-->
                                                    </div>
                                                    <!--end::Info-->
                                                </div>
                                                <!--end::Details-->
                                            </div>
                                        </div>
                                        <!--end::Navbar-->
                                        <!--begin::details View-->
                                        <div class="card mb-5 mb-xl-10" id="kt_profile_details_view">
                                            <!--begin::Card header-->
                                            <div class="card-header cursor-pointer">
                                                <!--begin::Card title-->
                                                <div class="card-title m-0">
                                                    <h3 class="fw-bolder m-0">User Details</h3>
                                                </div>
                                                <!--end::Card title-->
                                            </div>
                                            <!--begin::Card header-->
                                            <!--begin::Card body-->
                                            <div class="card-body p-9">
                                                <!--begin::Row-->
                                                <div class="row mb-7">
                                                    <!--begin::Label-->
                                                    <label class="col-lg-4 fw-bold text-muted">Full Name</label>
                                                    <!--end::Label-->
                                                    <!--begin::Col-->
                                                    <div class="col-lg-8">
                                                        <span class="fw-bolder fs-6 text-gray-800">{{ user.fullName }}</span>
                                                    </div>
                                                    <!--end::Col-->
                                                </div>

                                                {#{% if agent %}
                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Agency</label>
                                                    <div class="col-lg-8 fv-row">
                                                        <span class="fw-bold text-gray-800 fs-6">{{ agent.agency.name }}</span>
                                                    </div>
                                                </div>
                                                {% endif %}
                                                {% if agent %}
                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Contact Phone</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ agent.phone }}</span>
                                                    </div>
                                                </div>
                                                {% endif %}#}
                                                <div class="row mb-7">
                                                    <label class="col-lg-4 fw-bold text-muted">Contact Email</label>
                                                    <div class="col-lg-8 d-flex align-items-center">
                                                        <span class="fw-bolder fs-6 text-gray-800 me-2">{{ user.email }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <!--end::Card body-->
                                        </div>
                                        <!--end::details View-->

                                    </div>
                                    <!--end::Container-->
                                </div>
                                <!--end::Post-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function (e) {


        })
    </script>
{% endblock %}